const OPEN_URL='https://api.github.com/search/issues?q=org:lnflash+label:%22%F0%9F%92%B0+bounty%22+state:open&per_page=100';
const PAID_URL='https://api.github.com/search/issues?q=org:lnflash+label:%22paid%22+label:%22%F0%9F%92%B0+bounty%22+state:closed&per_page=100';
const LEVELS=['spark','flame','eruption','summit'];
const META={spark:{icon:'⚡',label:'Spark',cls:'badge-level-spark'},flame:{icon:'🔥',label:'Flame',cls:'badge-level-flame'},eruption:{icon:'🌋',label:'Eruption',cls:'badge-level-eruption'},summit:{icon:'🏔️',label:'Summit',cls:'badge-level-summit'}};
const STATUS_CLS={Open:'badge-open',Claimed:'badge-claimed','In Progress':'badge-in-progress','Under Review':'badge-review',Paid:'badge-paid'};
const loadingEl=document.getElementById('loading');
const errorEl=document.getElementById('error');
const container=document.getElementById('bounties-container');
function fmt(n){return new Intl.NumberFormat().format(n||0);}
function labels(issue){return (issue.labels||[]).map(l=>(l.name||'').toLowerCase());}
function repo(issue){const p=(issue.repository_url||'').split('/');return p.slice(-2).join('/');}
function level(issue){const l=labels(issue); if(l.some(x=>x.includes('summit')))return 'summit'; if(l.some(x=>x.includes('eruption')))return 'eruption'; if(l.some(x=>x.includes('flame')))return 'flame'; return 'spark';}
function status(issue){const l=labels(issue); if(l.includes('paid'))return 'Paid'; if(l.includes('review'))return 'Under Review'; if(l.includes('in-progress'))return 'In Progress'; if(l.includes('claimed'))return 'Claimed'; if(l.includes('approved'))return 'Open'; return issue.state==='closed'?'Paid':'Open';}
function satsFromText(t){if(!t) return 0; const pats=[/💰\s*([\d,]+)\s*sats?/gi,/([\d,]{3,})\s*sats?/gi]; for(const p of pats){let m; while((m=p.exec(t))){const n=parseInt((m[1]||'').replace(/[^\d]/g,''),10); if(n>0) return n;}} return 0;}
async function comments(issue){try{const r=await fetch(issue.comments_url,{headers:{Accept:'application/vnd.github+json'}}); if(!r.ok)return []; return await r.json();}catch{return [];}}
async function sats(issue){let n=satsFromText(issue.body)||satsFromText(issue.title); if(n) return n; if(issue.comments>0){const cs=await comments(issue); for(const c of cs){n=satsFromText(c.body); if(n) return n;}} for(const l of (issue.labels||[])){n=satsFromText(l.name); if(n)return n;} return 0;}
function categories(issue){const ignore=['approved','claimed','in-progress','review','paid']; return (issue.labels||[]).map(l=>l.name).filter(Boolean).filter(name=>{const n=name.toLowerCase(); if(n.includes('bounty'))return false; if(n.includes('spark')||n.includes('flame')||n.includes('eruption')||n.includes('summit'))return false; if(ignore.includes(n))return false; return true;});}
async function fetchIssues(url){const r=await fetch(url,{headers:{Accept:'application/vnd.github+json'}}); if(!r.ok) throw new Error('GitHub API '+r.status); const d=await r.json(); return d.items||[];}
function stats(items){document.getElementById('stat-total').textContent=String(items.length); document.getElementById('stat-sats').textContent=fmt(items.reduce((a,b)=>a+(b.sats||0),0)); document.getElementById('stat-open').textContent=String(items.filter(x=>x.status!=='Paid').length); document.getElementById('stat-done').textContent=String(items.filter(x=>x.status==='Paid').length);}
function render(items){container.innerHTML=''; const groups={spark:[],flame:[],eruption:[],summit:[]}; items.forEach(i=>groups[i.level].push(i)); LEVELS.forEach(lv=>{const list=groups[lv]; if(!list.length) return; const sec=document.createElement('section'); sec.className='level-section'; const h=document.createElement('div'); h.className='level-header'; const h2=document.createElement('h2'); h2.className='level-title'; h2.textContent=META[lv].icon+' '+META[lv].label; const c=document.createElement('span'); c.className='level-count'; c.textContent=String(list.length); h.appendChild(h2); h.appendChild(c); const grid=document.createElement('div'); grid.className='bounties-grid'; list.sort((a,b)=>(b.sats||0)-(a.sats||0)).forEach(b=>{const card=document.createElement('article'); card.className='card'+(b.status==='Paid'?' paid':''); const top=document.createElement('div'); top.className='card-top'; const t=document.createElement('h3'); t.className='card-title'; const a=document.createElement('a'); a.href=b.url; a.target='_blank'; a.rel='noopener'; a.textContent=b.title; t.appendChild(a); top.appendChild(t); const meta=document.createElement('div'); meta.className='card-meta'; const lb=document.createElement('span'); lb.className='badge '+META[b.level].cls; lb.textContent=META[b.level].icon+' '+META[b.level].label; const sb=document.createElement('span'); sb.className='badge '+(STATUS_CLS[b.status]||'badge-open'); sb.textContent=b.status; meta.appendChild(lb); meta.appendChild(sb); b.categories.forEach(cat=>{const cb=document.createElement('span'); cb.className='badge badge-cat'; cb.textContent=cat; meta.appendChild(cb);}); const foot=document.createElement('div'); foot.className='card-footer'; const rn=document.createElement('span'); rn.className='repo-name'; rn.textContent=b.repo; const sa=document.createElement('span'); sa.className='sats-amount'; sa.textContent=fmt(b.sats)+' sats'; const co=document.createElement('span'); co.className='comments'; co.textContent='💬 '+String(b.comments||0); foot.appendChild(rn); foot.appendChild(sa); foot.appendChild(co); card.appendChild(top); card.appendChild(meta); card.appendChild(foot); grid.appendChild(card);}); sec.appendChild(h); sec.appendChild(grid); container.appendChild(sec);});}
async function init(){try{const [open,paid]=await Promise.all([fetchIssues(OPEN_URL),fetchIssues(PAID_URL)]); const seen=new Set(); const merged=open.concat(paid).filter(i=>{if(seen.has(i.id))return false; seen.add(i.id); return true;}); const out=[]; for(const issue of merged){out.push({id:issue.id,title:issue.title,url:issue.html_url,repo:repo(issue),comments:issue.comments||0,level:level(issue),status:status(issue),sats:await sats(issue),categories:categories(issue)});} stats(out); render(out);}catch(e){errorEl.textContent='Failed to load bounties: '+e.message; errorEl.classList.remove('hidden');}finally{loadingEl.classList.add('hidden');}}
init();
